channels:
  - conda-forge
  - conda-forge/label/prerelease-jupyterlab  
dependencies:
  - numpy
  - scipy
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn 
##################################
  - xeus-cling=0.12.1
  - xtensor=0.23.0
  - xtensor-blas=0.19.0
  - boost
  - eigen
##################################
  - nodejs
  - xeus-python
  - notebook
  - ipywidgets>=7.6
  - jupyterlab=3
  - nbgitpuller
  - sphinx
  - jupyterlab-git
  - voila
  - rise
  - pip
  - pip: 
    - nbdime
    - yfinance
    - schedule 
    - panel
    - hvplot
    - get-all-tickers
    - pyDiffMap
    - arch
    - pandas_ta
    - xgboost
    - pandas_datareader
    - pycrypto
    - jupyterlab-spellchecker
    - pytest
    - pytest-cov
