channels:
  - conda-forge
  - conda-forge/label/prerelease-jupyterlab  
dependencies:
  - numpy
  - scipy
  - pandas
  - seaborn
  - matplotlib
  - scikit-learn 
  - xeus-cling=0.12.0
  - xtensor=0.23.0
  - xtensor-blas=0.19.0  
  - jupyterlab=2
  - nodejs
  - notebook=6
  - ptvsd
  - xeus-python=0.9.0
  - nbgitpuller
  - jupyterlab-git
  - voila
  - rise
  - pip
  - pip: 
    - nbdime
    - yfinance
    - schedule 
    - panel
    - hvplot
    - get-all-tickers
    - pyDiffMap
    - arch
    - pandas_ta
